"""Add is_anomaly column to expenses

Revision ID: 10e534acb33b
Revises: c4b84ed7b678
Create Date: 2026-06-17 15:20:44.995720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e534acb33b'
down_revision = 'c4b84ed7b678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_anomaly', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_anomaly')
    # ### end Alembic commands ###
